sudo: false
language: node_js
node_js:
  - "8"
  - "10"
branches:
  only:
    - master
notifications:
  email: false 
services:
  - mongodb

before_script:
  - npm prune
script:
  - npm install
after_success:
  - npm run lint
  - npm run test